# Generated by Django 3.0.4 on 2021-03-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sub_list',
            field=models.CharField(max_length=1000),
        ),
    ]
