# Generated by Django 3.0.4 on 2021-03-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210318_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='judge',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='mainNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='soupNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='subNum',
            field=models.IntegerField(null=True),
        ),
    ]
