# Generated by Django 3.0.4 on 2021-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210318_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mail',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
