# Generated by Django 3.0.4 on 2021-03-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_test_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
    ]
