# Generated by Django 3.0.4 on 2021-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_test_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='soup_list',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
