# Generated by Django 3.0.4 on 2021-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_test_soup_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='soup_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='sub_list',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
